# This is a basic workflow to help you get started with Actions

name: generate-mbtiles

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

env:
  AREA: colombia
  REGION: south-america

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download PBF file
        run: curl http://download.geofabrik.de/${REGION}/${AREA}-latest.osm.pbf -o ${AREA}.osm.pbf
        
      - name: Download ne_10m_urban_areas
        run: |
          mkdir -p landcover/ne_10m_urban_areas
          cd landcover/ne_10m_urban_areas && wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_urban_areas.zip
          cd landcover/ne_10m_urban_areas && unzip -o ne_10m_urban_areas.zip
      
      - name: Download ne_10m_antarctic_ice_shelves_polys
        run: |
          mkdir -p landcover/ne_10m_antarctic_ice_shelves_polys
          cd landcover/ne_10m_antarctic_ice_shelves_polys && wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_antarctic_ice_shelves_polys.zip
          cd landcover/ne_10m_antarctic_ice_shelves_polys && unzip -o ne_10m_antarctic_ice_shelves_polys.zip
          
      - name: Download ne_10m_glaciated_areas
        run: |
          mkdir -p landcover/ne_10m_glaciated_areas
          cd landcover/ne_10m_glaciated_areas && wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_glaciated_areas.zip
          cd landcover/ne_10m_glaciated_areas && unzip -o ne_10m_glaciated_areas.zip
      
      - name: Download water_polygons
        run: |
          mkdir -p coastline
          cd coastline && wget https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip
          cd coastline && unzip -o water-polygons-split-4326.zip
          cd coastline && mv water-polygons-split-4326/* .
    
      - name: Build openmaptiles-compatible mbtiles files of given area
        uses: systemed/tilemaker@v2.0.0
        with:
          # Required, same to --input
          input: ${{ env.AREA }}.osm.pbf
          # Required, same to --output. Could be a directory or a .mbtiles files
          output: ${{ env.AREA }}.mbtiles         
          
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
           name: mbtiles-colombia
           path: ${{ env.AREA }}.mbtiles
