# This is a basic workflow to help you get started with Actions
on:
  workflow_dispatch: ~
  schedule:
  - cron: 25 5 * * 1

name: planetiler-mbtiles

env:
  AREA: colombia
  REGION: south-america
  RAM: 2g

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'          

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g strip-ansi-cli@3.0.2
      
      - name: Download PlanetTiler
        run: |
          wget https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar -O planetiler.jar
    
      - name: 'Build MBTiles'
        run: |
          mkdir -p -v data
          java -Xms${{ env.RAM }} -Xmx${{ env.RAM }} -jar planetiler.jar --area="${{ env.AREA }}" --mbtiles=data/colombia.mbtiles --download --minzoom=0 --maxzoom=20 --languages=en,es 2>&1 | tee log
          ls -alh planetiler.jar | tee -a log
          cat log | strip-ansi > data/build-log.txt         
       
      - name: Get timestamp for release
        id: timestamp
        env:
          TZ: Europe/Amsterdam
        run: echo "timestamp=$(date +'Planetiles-%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
        
      - name: Release new graph
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: data/colombia.mbtiles,data/build-log.txt
          tag: ${{ steps.timestamp.outputs.timestamp }}
