# This is a basic workflow to help you get started with Actions
on:
  workflow_dispatch: ~
  schedule:
  - cron: 25 5 * * 1

name: tilemaker-mbtiles

env:
  AREA: colombia
  REGION: south-america

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download PBF file
        run: curl http://download.geofabrik.de/${REGION}/${AREA}-latest.osm.pbf -o ${AREA}.osm.pbf
        
      - name: Download ne_10m_urban_areas
        run: |
          mkdir -p -v landcover/ne_10m_urban_areas
          cd landcover/ne_10m_urban_areas
          ls -l
          wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_urban_areas.zip -O ne_10m_urban_areas.zip
          ls -l
          unzip -o ne_10m_urban_areas.zip
          cd ../../
      
      - name: Download ne_10m_antarctic_ice_shelves_polys
        run: |
          mkdir -p -v landcover/ne_10m_antarctic_ice_shelves_polys
          cd landcover/ne_10m_antarctic_ice_shelves_polys
          wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_antarctic_ice_shelves_polys.zip -O ne_10m_antarctic_ice_shelves_polys.zip 
          unzip -o ne_10m_antarctic_ice_shelves_polys.zip
          cd ../../
          
      - name: Download ne_10m_glaciated_areas
        run: |
          mkdir -p -v landcover/ne_10m_glaciated_areas
          cd landcover/ne_10m_glaciated_areas
          wget https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_glaciated_areas.zip -O ne_10m_glaciated_areas.zip
          unzip -o ne_10m_glaciated_areas.zip
          cd ../../
      
      - name: Download water_polygons
        run: |
          mkdir -p -v coastline
          cd coastline
          wget https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip -O water-polygons-split-4326.zip
          unzip -o water-polygons-split-4326.zip
          mv water-polygons-split-4326/* .
          cd ../
    
      - name: Build openmaptiles-compatible mbtiles files of given area
        uses: systemed/tilemaker@v3.0.0
        with:
          # Required, same to --input
          input: ${{ env.AREA }}.osm.pbf
          # Required, same to --output. Could be a directory or a .mbtiles files
          output: ${{ env.AREA }}.mbtiles         
          
      - name: Get timestamp for release
        id: timestamp
        env:
          TZ: Europe/Amsterdam
        run: echo "timestamp=$(date +'Tilemaker-%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
        
      - name: Release new graph        
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: colombia.mbtiles
          tag: ${{ steps.timestamp.outputs.timestamp }}
